### PR TITLE
updated Home page text and added logos

### PR DESCRIPTION
**Pull request by Spanarchie**
Adding Text and logos to home page

### CODE REVIEW

**Comment by juancarloshg** [comment]
I am getting an error when installing the npm packages in this new folder:

npm ERR! angular2-sample-app@0.0.0 postinstall: `tsd reinstall --clean && tsd link && tsd rebundle && gulp check.versions && gulp postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-sample-app@0.0.0 postinstall script 'tsd reinstall --clean && tsd link && tsd rebundle && gulp check.versions && gulp postinstall'.

**Comment by juancarloshg** [comment]
It seems to be a problem with this:

⨯ Unable to compile TypeScript

tools\typings\tsd\del\del.d.ts (10,27): Cannot find module 'glob'. (2307)

**Comment by juancarloshg** [comment]
After exploring a bit more, I found out my glob file was empty and just pasted the contents of the glob file in the other directory. I guess this may be a problem with the glob dependency, maybe they removed it from npm.

It is working now. Great job! Looks much better now with the text and logos

**Comment by juancarloshg** [comment]
You removed the .gitignore file in the new version. Is that on purpose?

**Comment by Spanarchie** [comment]
God no!!!!!!!!!! Please replace 😨

**Pull request merged**
