### PR TITLE
push angular2-sample-app

### PR DESCRIPTION
**Pull request by Dean-Foulds**
@amartin78 @juancarloshg @Spanarchie, I have pulled and tested this and it works.

### CODE REVIEW

**Comment by amartin78** [comment]
Ok

**Comment by Dean-Foulds** [comment]
Very good work as well by the way :)

**Comment by Dean-Foulds** [comment]
I raised a pull request for you because it functions but maybe the others
want to go over it to make sure they ate happy before merge

**Comment by juancarloshg** [comment]
Works here too :)

**Pull request merged**
