### PR TITLE
initial app commit

### PR DESCRIPTION
**Pull request by Dean-Foulds**
@amartin78 , @itestedthis1 and @juancarloshg 

Would you be so kind as to check this pull request for me please?  It is the angular 2 app details added.  Deep in the directory is the code for the web app so we can play with it prior to next Wednesday.

Thank you

### CODE REVIEW

**Comment by juancarloshg** [comment]
I can only see an empty "web" folder there, I don't know if I'm doing something wrong

**Comment by amartin78** [comment]
I also found an empty folder.

**Comment by Dean-Foulds** [comment]
I need to push again. I lost connection

**Comment by Spanarchie** [comment]
Hi Dean did you add the files before the commit.
a mistake I still frequently do allowing the commiting
of an empty file ( not sure with sub module)

Should see something similar to https://github.com/civicreactor/CareHomeInfo/pull/3/files
where all the new files are visible for review ;-)

**Comment by Dean-Foulds** [comment]
I am looking into this today.  Locally I have all the files and working but
nee to jump on and push them, I hope

On Sat, Nov 12, 2016 at 11:09 AM, Colin Moore-Hill <notifications@github.com

**Pull request closed without merging**
